In [2]:
from sklearn import svm, datasets
import pandas as pd

In [7]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
# displaying the contents of iris
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [13]:
# displaying the data of 5 rows
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
# displaying name for each four columns
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [11]:
# displaying target values and target names
print(iris.target)
print(iris.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [12]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [17]:
# concatenate target value and into the dataframe
df['target'] = iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [24]:
df['target_names'] = df['target'].apply(lambda x:iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_names  
0       0       setosa  
1       0       setosa  
2       0       setosa  
3       0       setosa  
4       0       setosa

In [21]:
print(pd.unique(iris.target))
print(iris.target_names)

[0 1 2]
['setosa' 'versicolor' 'virginica']


In [22]:
# splitting the dataset for each target values
# setosa.
df1 = df[df.target==0]
# versicolor 
df2 = df[df.target==1]
# virginica
df3 = df[df.target==2]

In [15]:
# import plotting library 'matplotlib'
import matplotlib.pyplot as plt

In [ ]:
# plot scatter plot for setosa
plt.scatter(df1)

In [76]:
X = df[["sepal length (cm)","sepal width (cm)", "petal length (cm)", "petal width (cm)"]].values
y = df.target.values

In [99]:
# print first five rows of X and the value of y to check it works
print(X[:3])
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [61]:
# import train_test_split
from sklearn.model_selection import train_test_split

In [62]:
# split the X and y dataset into traininga and testing dataset
# displaying total train and test set for each X and y dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
print(len(X_train), len(X_test))
print(len(y_train), len(y_test))

120 30
120 30


## Train Test split 

In [63]:
# importing machine learning model library
from sklearn import svm

In [64]:
# train the model and predict using the test dataset ie y
model = svm.SVC(kernel='rbf', C=30, gamma='auto')
model.fit(X_train, y_train)
model.predict(X_test)

array([2, 0, 0, 1, 2, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 1, 0, 0, 2, 1, 2, 0,
       0, 0, 0, 2, 2, 1, 0, 2])

In [98]:
# lets compare with the actual result
y_test

array([2, 0, 0, 1, 1, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 1, 0, 0, 2, 1, 2, 0,
       0, 0, 0, 1, 2, 1, 0, 2])

## Cross Validation Score

In [89]:
# trying another type of model_selection called kfold or cross_validation_score
# cross validation score will split a dataset into separate dataset and train the model cv=N times returning N score result
from sklearn.model_selection import cross_val_score

In [90]:
cross_val_score(svm.SVC(kernel='linear', C=10, gamma='auto'), X, y, cv=5 )

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [91]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma='auto'), X, y, cv=5 )

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [92]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'), X, y, cv=5 )

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [93]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'), X, y, cv=3 )

array([0.98, 0.94, 0.98])

In [94]:
# lets calculate the above values and take average for each 
import numpy as np

In [97]:
kernels = ['linear', 'rbf']
Cs = [1, 5, 10]
avg_scores = {}
for x in kernels:
    for cval in Cs:
        cvs = cross_val_score(svm.SVC(kernel=x, C=cval, gamma='auto'),X, y, cv=5)
        avg_scores[x+"_"+str(cval)] = np.mean(cvs)
avg_scores

{'linear_1': 0.9800000000000001,
 'linear_5': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'rbf_1': 0.9800000000000001,
 'rbf_5': 0.9800000000000001,
 'rbf_10': 0.9800000000000001}

## GridSearchView
grid search view allows us to do the above long nested for loop cross validation into a few lines of code

In [100]:
from sklearn.model_selection import GridSearchCV

In [104]:
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'kernel': ['linear', 'rbf'],
    'C': [1, 10, 20]
}, cv=5, return_train_score=False)

clf.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']})

In [106]:
clf.cv_results_

{'mean_fit_time': array([0.00119648, 0.00119877, 0.00099726, 0.00099878, 0.00099683,
        0.00099745]),
 'std_fit_time': array([3.99303465e-04, 3.99007293e-04, 2.78041453e-07, 3.31873181e-06,
        7.23159356e-07, 1.16800773e-07]),
 'mean_score_time': array([0.00019956, 0.0013937 , 0.00059834, 0.00079684, 0.00019951,
        0.0007978 ]),
 'std_score_time': array([0.00039911, 0.00079685, 0.00048854, 0.00039844, 0.00039902,
        0.0003989 ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C':

In [107]:
# the above GridSearchCV result is in the form of dictionary so we can clput it inside pandas DataFrame and make it easire to read
gscv_result = pd.DataFrame(clf.cv_results_)

gscv_result

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001196  3.993035e-04         0.000200        0.000399       1   
1       0.001199  3.990073e-04         0.001394        0.000797       1   
2       0.000997  2.780415e-07         0.000598        0.000489      10   
3       0.000999  3.318732e-06         0.000797        0.000398      10   
4       0.000997  7.231594e-07         0.000200        0.000399      20   
5       0.000997  1.168008e-07         0.000798        0.000399      20   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
1          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
2       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
5          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.900000           0.966667                1.0   
3                1.0           0.966667           0.966667                1.0   
4                1.0           0.900000           0.933333                1.0   
5                1.0           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.973333        0.038873                4  
3         0.980000        0.016330                1  
4         0.966667        0.042164                6  
5         0.966667        0.036515                5

In [108]:
gscv_result.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_C', 'param_kernel', 'params', 'split0_test_score',
       'split1_test_score', 'split2_test_score', 'split3_test_score',
       'split4_test_score', 'mean_test_score', 'std_test_score',
       'rank_test_score'],
      dtype='object')

In [109]:
gscv_result[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1       1          rbf         0.980000
2      10       linear         0.973333
3      10          rbf         0.980000
4      20       linear         0.966667
5      20          rbf         0.966667

In [110]:
# displaying properties of GridSearchCV model
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 '

In [112]:
clf.best_score_

0.9800000000000001

In [111]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [113]:
clf.best_estimator_

SVC(C=1, gamma='auto', kernel='linear')

In [114]:
clf.best_index_

0

### SOME USEFUL NOTES

In [37]:
# way 1: display specific column value
df.iloc[:,0:2]

sepal length (cm)  sepal width (cm)
0                  5.1               3.5
1                  4.9               3.0
2                  4.7               3.2
3                  4.6               3.1
4                  5.0               3.6
..                 ...               ...
145                6.7               3.0
146                6.3               2.5
147                6.5               3.0
148                6.2               3.4
149                5.9               3.0

[150 rows x 2 columns]

In [40]:
# way 2: display specific column value
df.loc[:,["sepal length (cm)","sepal width (cm)"]]

sepal length (cm)  sepal width (cm)
0                  5.1               3.5
1                  4.9               3.0
2                  4.7               3.2
3                  4.6               3.1
4                  5.0               3.6
..                 ...               ...
145                6.7               3.0
146                6.3               2.5
147                6.5               3.0
148                6.2               3.4
149                5.9               3.0

[150 rows x 2 columns]